### ISSUE TITLE
private information disclosed

### ISSUE THREAD

**Issue by shamim261** [nazmul-nhb/auth-moha-milon#1]
sir, firebase er apikey private rakhte hobe🥲

**Comment by nazmul-nhb** [comment]
thank you dear for the pointing it out.❤️❤️❤️
i'm already aware of this issue... these are just the practice tasks... i started learning/using firebase 5 days ago as a part of my ongoing course... 

তারপর কেমন আছো?

**Comment by nazmul-nhb** [comment]
> sir, firebase er apikey private rakhte hobe🥲

thank you dear for pointing it out.❤️❤️❤️
i'm already aware of this issue... these are just the practice tasks... i started learning/using firebase 5 days ago as a part of my ongoing course... 

তারপর কেমন আছো?

**Comment by shamim261** [comment]
eito sir bhalo..
kar course follow kortechen?

**Comment by nazmul-nhb** [comment]
> eito sir bhalo..
> kar course follow kortechen?
> 

sent you msg on instagram. please, check it...
